#Series

A Pandas Series is a one-dimensional, labeled array capable of holding data of any type

In [2]:
!pip install numpy pandas
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (2.2.5)
Requirement already satisfied: pandas in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
strings = ["Alpha","Beta","Gama"]
integers = [10,20,30]
array = np.array([40,50,60])
dictionary = {1:"JAVA" , 2:"PYTHON" , 3:"C++"}

#Priting String

In [4]:
print(pd.Series(strings))

0    Alpha
1     Beta
2     Gama
dtype: object

#print integers

In [5]:
print(pd.Series(integers))

0    10
1    20
2    30
dtype: int64

#Print array

In [6]:
print(pd.Series(array))

0    40
1    50
2    60
dtype: int64

#Print dictionary

In [7]:
print(pd.Series(dictionary))

1      JAVA
2    PYTHON
3       C++
dtype: object

#Replacing Index

In [8]:
print(pd.Series(integers,index = ["a","b","c"]) )#Single inverted commas can be  used too example'a','b'

a    10
b    20
c    30
dtype: int64

#Using diff series for index

In [9]:
print(pd.Series(integers,index = strings))

Alpha    10
Beta     20
Gama     30
dtype: int64

In [10]:
data = {
    "Name": ["Aarav", "Priya", "Rahul"],
    "Salary": [45000, 52000, 48000],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)

df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [11]:
data = [
    ["Aarav", 45000, "Pune"],
    ["Priya", 52000, "Mumbai"],
    ["Rahul", 48000, "Delhi"]
]

df = pd.DataFrame(data, columns=["Name", "Salary", "City"])

df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [12]:
df["Name"]

0    Aarav
1    Priya
2    Rahul
Name: Name, dtype: object

In [13]:
df[["Name", "Salary"]]

    Name  Salary
0  Aarav   45000
1  Priya   52000
2  Rahul   48000

In [14]:
df.loc[0]

Name      Aarav
Salary    45000
City       Pune
Name: 0, dtype: object

In [15]:
df.loc[0:1]

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai

In [16]:
df.loc[0:1, ["Name", "City"]]

    Name    City
0  Aarav    Pune
1  Priya  Mumbai

In [17]:
df.iloc[0]

Name      Aarav
Salary    45000
City       Pune
Name: 0, dtype: object

In [18]:
df.iloc[0:2]

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai

In [19]:
df["Age"] = [24,24,21]
df

    Name  Salary    City  Age
0  Aarav   45000    Pune   24
1  Priya   52000  Mumbai   24
2  Rahul   48000   Delhi   21

#Drop Function

In [20]:
df.drop("Age",axis=1)

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [21]:
df

    Name  Salary    City  Age
0  Aarav   45000    Pune   24
1  Priya   52000  Mumbai   24
2  Rahul   48000   Delhi   21

In [22]:
df.drop("Age",axis=1,inplace=True)

In [23]:
df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [24]:
new_data = pd.DataFrame([
    ["Arjun", 30000, "Pune"],
    ["Atul", 45000, "Mumbai"],
    ["Pratik", 60400, "Delhi"]
], columns=["Name", "Salary", "City"])

df = pd.concat([df, new_data], ignore_index=True)

In [25]:
df

     Name  Salary    City
0   Aarav   45000    Pune
1   Priya   52000  Mumbai
2   Rahul   48000   Delhi
3   Arjun   30000    Pune
4    Atul   45000  Mumbai
5  Pratik   60400   Delhi

In [26]:
df["Age"] = [20,30,35,26,25,27]

In [27]:
df

     Name  Salary    City  Age
0   Aarav   45000    Pune   20
1   Priya   52000  Mumbai   30
2   Rahul   48000   Delhi   35
3   Arjun   30000    Pune   26
4    Atul   45000  Mumbai   25
5  Pratik   60400   Delhi   27

#I want the Data of People who are from Pune

== , != , & , > , < , <= ,>= , |

In [28]:
df[df["City"]=="Pune"]

    Name  Salary  City  Age
0  Aarav   45000  Pune   20
3  Arjun   30000  Pune   26

#Person From Pune Whose Age is Greater than 25

In [29]:
df[(df["City"] == "Pune") & (df["Age"] > 25)]

    Name  Salary  City  Age
3  Arjun   30000  Pune   26

#People who are not From Pune

In [30]:
df[(df["City"] != "Pune") ]

     Name  Salary    City  Age
1   Priya   52000  Mumbai   30
2   Rahul   48000   Delhi   35
4    Atul   45000  Mumbai   25
5  Pratik   60400   Delhi   27

Missing Values

In [31]:
data = {
    "Name": ["Arun", "Atul", "Pratik", "Rahul", "Sneha", "Priya", "Rohan", "Aisha"],
    "Age": [25, 30, np.nan, 28, 32, np.nan, 26, 29],
    "Salary": [30000, np.nan, 45000, 52000, np.nan, 48000, 35000, 60000],
    "City": ["Pune", "Mumbai", "Delhi", np.nan, "Pune", "Mumbai", np.nan, "Delhi"],
    "Experience": [2, 5, np.nan, 4, 7, 3, np.nan, 6]
}

df = pd.DataFrame(data)

df

     Name   Age   Salary    City  Experience
0    Arun  25.0  30000.0    Pune         2.0
1    Atul  30.0      NaN  Mumbai         5.0
2  Pratik   NaN  45000.0   Delhi         NaN
3   Rahul  28.0  52000.0     NaN         4.0
4   Sneha  32.0      NaN    Pune         7.0
5   Priya   NaN  48000.0  Mumbai         3.0
6   Rohan  26.0  35000.0     NaN         NaN
7   Aisha  29.0  60000.0   Delhi         6.0

Checking Null Values

In [32]:
df.isnull()

    Name    Age  Salary   City  Experience
0  False  False   False  False       False
1  False  False    True  False       False
2  False   True   False  False        True
3  False  False   False   True       False
4  False  False    True  False       False
5  False   True   False  False       False
6  False  False   False   True        True
7  False  False   False  False       False

Total number of Null Values

In [33]:
df.isnull().sum()

Name          0
Age           2
Salary        2
City          2
Experience    2
dtype: int64

TO CHECK VALUES WHICH ARE NOT NULL

In [34]:
df[df.notnull().all(axis=1)]

    Name   Age   Salary   City  Experience
0   Arun  25.0  30000.0   Pune         2.0
7  Aisha  29.0  60000.0  Delhi         6.0

To drop null Values rows

In [35]:
df.dropna()

    Name   Age   Salary   City  Experience
0   Arun  25.0  30000.0   Pune         2.0
7  Aisha  29.0  60000.0  Delhi         6.0

Drop only those rows who have less 3 non values

In [36]:
df

     Name   Age   Salary    City  Experience
0    Arun  25.0  30000.0    Pune         2.0
1    Atul  30.0      NaN  Mumbai         5.0
2  Pratik   NaN  45000.0   Delhi         NaN
3   Rahul  28.0  52000.0     NaN         4.0
4   Sneha  32.0      NaN    Pune         7.0
5   Priya   NaN  48000.0  Mumbai         3.0
6   Rohan  26.0  35000.0     NaN         NaN
7   Aisha  29.0  60000.0   Delhi         6.0

In [37]:
df.dropna(thresh=5)

    Name   Age   Salary   City  Experience
0   Arun  25.0  30000.0   Pune         2.0
7  Aisha  29.0  60000.0  Delhi         6.0

Filling out Missing Values

In [38]:
df.fillna(0)

     Name   Age   Salary    City  Experience
0    Arun  25.0  30000.0    Pune         2.0
1    Atul  30.0      0.0  Mumbai         5.0
2  Pratik   0.0  45000.0   Delhi         0.0
3   Rahul  28.0  52000.0       0         4.0
4   Sneha  32.0      0.0    Pune         7.0
5   Priya   0.0  48000.0  Mumbai         3.0
6   Rohan  26.0  35000.0       0         0.0
7   Aisha  29.0  60000.0   Delhi         6.0

In [39]:
df = df.fillna(df.mean(numeric_only=True))

In [40]:
df

     Name        Age   Salary    City  Experience
0    Arun  25.000000  30000.0    Pune         2.0
1    Atul  30.000000  45000.0  Mumbai         5.0
2  Pratik  28.333333  45000.0   Delhi         4.5
3   Rahul  28.000000  52000.0     NaN         4.0
4   Sneha  32.000000  45000.0    Pune         7.0
5   Priya  28.333333  48000.0  Mumbai         3.0
6   Rohan  26.000000  35000.0     NaN         4.5
7   Aisha  29.000000  60000.0   Delhi         6.0

In [41]:
df["City"]= df["City"].fillna("Agra")

In [42]:
df

     Name        Age   Salary    City  Experience
0    Arun  25.000000  30000.0    Pune         2.0
1    Atul  30.000000  45000.0  Mumbai         5.0
2  Pratik  28.333333  45000.0   Delhi         4.5
3   Rahul  28.000000  52000.0    Agra         4.0
4   Sneha  32.000000  45000.0    Pune         7.0
5   Priya  28.333333  48000.0  Mumbai         3.0
6   Rohan  26.000000  35000.0    Agra         4.5
7   Aisha  29.000000  60000.0   Delhi         6.0

In [43]:
df.isnull().sum()

Name          0
Age           0
Salary        0
City          0
Experience    0
dtype: int64

Merging  Two Dataframes

In [44]:
df1 = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Aarav", "Priya", "Rahul", "Sneha", "Vikram"],
    "Department_ID": [1, 2, 1, 3, 2]
})

df1

   Employee_ID    Name  Department_ID
0          101   Aarav              1
1          102   Priya              2
2          103   Rahul              1
3          104   Sneha              3
4          105  Vikram              2

In [45]:
df2 = pd.DataFrame({
    "Department_ID": [1, 2, 3, 4],
    "Department": ["IT", "HR", "Finance", "Marketing"],
    "Location": ["Pune", "Mumbai", "Delhi", "Bangalore"]
})

df2

   Department_ID Department   Location
0              1         IT       Pune
1              2         HR     Mumbai
2              3    Finance      Delhi
3              4  Marketing  Bangalore

In [46]:
pd.merge(df1, df2, on="Department_ID", how="inner")

   Employee_ID    Name  Department_ID Department Location
0          101   Aarav              1         IT     Pune
1          102   Priya              2         HR   Mumbai
2          103   Rahul              1         IT     Pune
3          104   Sneha              3    Finance    Delhi
4          105  Vikram              2         HR   Mumbai

In [47]:
pd.merge(df1, df2, on="Department_ID", how="outer")

   Employee_ID    Name  Department_ID Department   Location
0        101.0   Aarav              1         IT       Pune
1        103.0   Rahul              1         IT       Pune
2        102.0   Priya              2         HR     Mumbai
3        105.0  Vikram              2         HR     Mumbai
4        104.0   Sneha              3    Finance      Delhi
5          NaN     NaN              4  Marketing  Bangalore

#Concatination

In [48]:


df3 = pd.DataFrame({
    "Name": ["Aarav", "Priya", "Rahul"],
    "Salary": [45000, 52000, 48000],
    "City": ["Pune", "Mumbai", "Delhi"]
})

df3

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [49]:
df4 = pd.DataFrame({
    "Name": ["Sneha", "Rohan", "Ananya"],
    "Salary": [55000, 47000, 60000],
    "City": ["Nashik", "Pune", "Mumbai"]
})

df4

     Name  Salary    City
0   Sneha   55000  Nashik
1   Rohan   47000    Pune
2  Ananya   60000  Mumbai

In [50]:
pd.concat([df3,df4])

     Name  Salary    City
0   Aarav   45000    Pune
1   Priya   52000  Mumbai
2   Rahul   48000   Delhi
0   Sneha   55000  Nashik
1   Rohan   47000    Pune
2  Ananya   60000  Mumbai

In [51]:
df5 = pd.DataFrame({
    "Name": ["Aarav", "Priya", "Rahul"],
    "Salary": [45000, 50000, 48000]
}, index=[1, 2, 3])

df5

    Name  Salary
1  Aarav   45000
2  Priya   50000
3  Rahul   48000

In [52]:
df6 = pd.DataFrame({
    "Department": ["IT", "HR", "Finance"]
}, index=[1, 2, 3])

df6

  Department
1         IT
2         HR
3    Finance

In [53]:
result = df5.join(df6)

print(result)

    Name  Salary Department
1  Aarav   45000         IT
2  Priya   50000         HR
3  Rahul   48000    Finance

In [54]:


data = {
    "Ticket_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
    "Passenger": ["Rahul", "Priya", "Amit", "Sneha", "Karan", "Anjali",
                  "Rohit", "Neha", "Vikram", "Pooja", "Arjun", "Meera"],
    "Train": ["Rajdhani", "Shatabdi", "Rajdhani", "Duronto",
              "Shatabdi", "Rajdhani", "Duronto", "Shatabdi",
              "Rajdhani", "Duronto", "Shatabdi", "Rajdhani"],
    "From": ["Pune", "Mumbai", "Pune", "Delhi",
             "Mumbai", "Pune", "Delhi", "Mumbai",
             "Pune", "Delhi", "Mumbai", "Pune"],
    "To": ["Delhi", "Pune", "Delhi", "Mumbai",
           "Pune", "Delhi", "Mumbai", "Pune",
           "Delhi", "Mumbai", "Pune", "Delhi"],
    "Class": ["AC 2-Tier", "AC Chair", "AC 3-Tier", "Sleeper",
              "AC Chair", "AC 2-Tier", "Sleeper", "AC Chair",
              "AC 3-Tier", "Sleeper", "AC Chair", "AC 2-Tier"],
    "Passengers": [2, 1, 3, 2, 1, 4, 2, 3, 1, 2, 4, 2],
    "Fare": [2400, 1200, 3600, 1600, 1200, 4800,
             1600, 3600, 1200, 1600, 4800, 2400]
}

df = pd.DataFrame(data)

df

    Ticket_ID Passenger     Train    From      To      Class  Passengers  Fare
0         101     Rahul  Rajdhani    Pune   Delhi  AC 2-Tier           2  2400
1         102     Priya  Shatabdi  Mumbai    Pune   AC Chair           1  1200
2         103      Amit  Rajdhani    Pune   Delhi  AC 3-Tier           3  3600
3         104     Sneha   Duronto   Delhi  Mumbai    Sleeper           2  1600
4         105     Karan  Shatabdi  Mumbai    Pune   AC Chair           1  1200
5         106    Anjali  Rajdhani    Pune   Delhi  AC 2-Tier           4  4800
6         107     Rohit   Duronto   Delhi  Mumbai    Sleeper           2  1600
7         108      Neha  Shatabdi  Mumbai    Pune   AC Chair           3  3600
8         109    Vikram  Rajdhani    Pune   Delhi  AC 3-Tier           1  1200
9         110     Pooja   Duronto   Delhi  Mumbai    Sleeper           2  1600
10        111     Arjun  Shatabdi  Mumbai    Pune   AC Chair           4  4800
11        112     Meera  Rajdhani    Pune   Delhi  AC 2-Tier           2  2400

In [55]:
df.groupby("Train")["Fare"]

In [56]:
fare = df.groupby("Train")["Fare"]
for x,v in fare:
    print("\n",x,"\n",v)

 Duronto
 3    1600
6    1600
9    1600
Name: Fare, dtype: int64

 Rajdhani
 0     2400
2     3600
5     4800
8     1200
11    2400
Name: Fare, dtype: int64

 Shatabdi
 1     1200
4     1200
7     3600
10    4800
Name: Fare, dtype: int64

In [57]:
df.groupby("Train")["Fare"].sum()

Train
Duronto      4800
Rajdhani    14400
Shatabdi    10800
Name: Fare, dtype: int64

In [58]:
df.groupby("From")["From"].count()

From
Delhi     3
Mumbai    4
Pune      5
Name: From, dtype: int64

In [59]:
df.groupby("Train")["Fare"].agg(["sum", "mean", "min", "max"])

            sum    mean   min   max
Train
Duronto    4800  1600.0  1600  1600
Rajdhani  14400  2880.0  1200  4800
Shatabdi  10800  2700.0  1200  4800