#Series

A Pandas Series is a one-dimensional, labeled array capable of holding data of any type

In [1]:
!pip install numpy pandas
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (2.2.5)
Requirement already satisfied: pandas in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
strings = ["Alpha","Beta","Gama"]
integers = [10,20,30]
array = np.array([40,50,60])
dictionary = {1:"JAVA" , 2:"PYTHON" , 3:"C++"}

#Priting String

In [3]:
print(pd.Series(strings))

0    Alpha
1     Beta
2     Gama
dtype: object

#print integers

In [4]:
print(pd.Series(integers))

0    10
1    20
2    30
dtype: int64

#Print array

In [5]:
print(pd.Series(array))

0    40
1    50
2    60
dtype: int64

#Print dictionary

In [6]:
print(pd.Series(dictionary))

1      JAVA
2    PYTHON
3       C++
dtype: object

#Replacing Index

In [7]:
print(pd.Series(integers,index = ["a","b","c"]) )#Single inverted commas can be  used too example'a','b'

a    10
b    20
c    30
dtype: int64

#Using diff series for index

In [8]:
print(pd.Series(integers,index = strings))

Alpha    10
Beta     20
Gama     30
dtype: int64

In [9]:
data = {
    "Name": ["Aarav", "Priya", "Rahul"],
    "Salary": [45000, 52000, 48000],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)

df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [10]:
data = [
    ["Aarav", 45000, "Pune"],
    ["Priya", 52000, "Mumbai"],
    ["Rahul", 48000, "Delhi"]
]

df = pd.DataFrame(data, columns=["Name", "Salary", "City"])

df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [11]:
df["Name"]

0    Aarav
1    Priya
2    Rahul
Name: Name, dtype: object

In [12]:
df[["Name", "Salary"]]

    Name  Salary
0  Aarav   45000
1  Priya   52000
2  Rahul   48000

In [13]:
df.loc[0]

Name      Aarav
Salary    45000
City       Pune
Name: 0, dtype: object

In [14]:
df.loc[0:1]

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai

In [15]:
df.loc[0:1, ["Name", "City"]]

    Name    City
0  Aarav    Pune
1  Priya  Mumbai

In [16]:
df.iloc[0]

Name      Aarav
Salary    45000
City       Pune
Name: 0, dtype: object

In [17]:
df.iloc[0:2]

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai

In [18]:
df["Age"] = [24,24,21]
df

    Name  Salary    City  Age
0  Aarav   45000    Pune   24
1  Priya   52000  Mumbai   24
2  Rahul   48000   Delhi   21

#Drop Function

In [19]:
df.drop("Age",axis=1)

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [20]:
df

    Name  Salary    City  Age
0  Aarav   45000    Pune   24
1  Priya   52000  Mumbai   24
2  Rahul   48000   Delhi   21

In [21]:
df.drop("Age",axis=1,inplace=True)

In [22]:
df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [23]:
new_data = pd.DataFrame([
    ["Arjun", 30000, "Pune"],
    ["Atul", 45000, "Mumbai"],
    ["Pratik", 60400, "Delhi"]
], columns=["Name", "Salary", "City"])

df = pd.concat([df, new_data], ignore_index=True)

In [24]:
df

     Name  Salary    City
0   Aarav   45000    Pune
1   Priya   52000  Mumbai
2   Rahul   48000   Delhi
3   Arjun   30000    Pune
4    Atul   45000  Mumbai
5  Pratik   60400   Delhi

In [28]:
df["Age"] = [20,30,35,26,25,27]

In [29]:
df

     Name  Salary    City  Age
0   Aarav   45000    Pune   20
1   Priya   52000  Mumbai   30
2   Rahul   48000   Delhi   35
3   Arjun   30000    Pune   26
4    Atul   45000  Mumbai   25
5  Pratik   60400   Delhi   27

#I want the Data of People who are from Pune

In [30]:
df[df["City"]=="Pune"]

    Name  Salary  City  Age
0  Aarav   45000  Pune   20
3  Arjun   30000  Pune   26

#Person From Pune Whose Age is Greater than 25

In [34]:
df[(df["City"] == "Pune") & (df["Age"] > 25)]

    Name  Salary  City  Age
3  Arjun   30000  Pune   26

#People who are not From Pune

In [35]:
df[(df["City"] != "Pune") ]

     Name  Salary    City  Age
1   Priya   52000  Mumbai   30
2   Rahul   48000   Delhi   35
4    Atul   45000  Mumbai   25
5  Pratik   60400   Delhi   27

Missing Values

In [36]:
data = {
    "Name": ["Arun", "Atul", "Pratik", "Rahul", "Sneha", "Priya", "Rohan", "Aisha"],
    "Age": [25, 30, np.nan, 28, 32, np.nan, 26, 29],
    "Salary": [30000, np.nan, 45000, 52000, np.nan, 48000, 35000, 60000],
    "City": ["Pune", "Mumbai", "Delhi", np.nan, "Pune", "Mumbai", np.nan, "Delhi"],
    "Experience": [2, 5, np.nan, 4, 7, 3, np.nan, 6]
}

df = pd.DataFrame(data)

df

     Name   Age   Salary    City  Experience
0    Arun  25.0  30000.0    Pune         2.0
1    Atul  30.0      NaN  Mumbai         5.0
2  Pratik   NaN  45000.0   Delhi         NaN
3   Rahul  28.0  52000.0     NaN         4.0
4   Sneha  32.0      NaN    Pune         7.0
5   Priya   NaN  48000.0  Mumbai         3.0
6   Rohan  26.0  35000.0     NaN         NaN
7   Aisha  29.0  60000.0   Delhi         6.0

Checking Null Values

In [37]:
df.isnull()

    Name    Age  Salary   City  Experience
0  False  False   False  False       False
1  False  False    True  False       False
2  False   True   False  False        True
3  False  False   False   True       False
4  False  False    True  False       False
5  False   True   False  False       False
6  False  False   False   True        True
7  False  False   False  False       False

Total number of Null Values

In [38]:
df.isnull().sum()

Name          0
Age           2
Salary        2
City          2
Experience    2
dtype: int64

TO CHECK VALUES WHICH ARE NOT NULL

In [44]:
df[df.notnull().all(axis=1)]

    Name   Age   Salary   City  Experience
0   Arun  25.0  30000.0   Pune         2.0
7  Aisha  29.0  60000.0  Delhi         6.0

To drop null Values rows

In [45]:
df.dropna()

    Name   Age   Salary   City  Experience
0   Arun  25.0  30000.0   Pune         2.0
7  Aisha  29.0  60000.0  Delhi         6.0

Drop only those rows who have less 3 non values

In [46]:
df.dropna(thresh=3)

     Name   Age   Salary    City  Experience
0    Arun  25.0  30000.0    Pune         2.0
1    Atul  30.0      NaN  Mumbai         5.0
2  Pratik   NaN  45000.0   Delhi         NaN
3   Rahul  28.0  52000.0     NaN         4.0
4   Sneha  32.0      NaN    Pune         7.0
5   Priya   NaN  48000.0  Mumbai         3.0
6   Rohan  26.0  35000.0     NaN         NaN
7   Aisha  29.0  60000.0   Delhi         6.0

Filling out Missing Values

In [47]:
df.fillna(0)

     Name   Age   Salary    City  Experience
0    Arun  25.0  30000.0    Pune         2.0
1    Atul  30.0      0.0  Mumbai         5.0
2  Pratik   0.0  45000.0   Delhi         0.0
3   Rahul  28.0  52000.0       0         4.0
4   Sneha  32.0      0.0    Pune         7.0
5   Priya   0.0  48000.0  Mumbai         3.0
6   Rohan  26.0  35000.0       0         0.0
7   Aisha  29.0  60000.0   Delhi         6.0

In [49]:
df = df.fillna(df.mean(numeric_only=True))

In [50]:
df

     Name        Age   Salary    City  Experience
0    Arun  25.000000  30000.0    Pune         2.0
1    Atul  30.000000  45000.0  Mumbai         5.0
2  Pratik  28.333333  45000.0   Delhi         4.5
3   Rahul  28.000000  52000.0     NaN         4.0
4   Sneha  32.000000  45000.0    Pune         7.0
5   Priya  28.333333  48000.0  Mumbai         3.0
6   Rohan  26.000000  35000.0     NaN         4.5
7   Aisha  29.000000  60000.0   Delhi         6.0

In [51]:
df["City"]= df["City"].fillna("Agra")

In [52]:
df

     Name        Age   Salary    City  Experience
0    Arun  25.000000  30000.0    Pune         2.0
1    Atul  30.000000  45000.0  Mumbai         5.0
2  Pratik  28.333333  45000.0   Delhi         4.5
3   Rahul  28.000000  52000.0    Agra         4.0
4   Sneha  32.000000  45000.0    Pune         7.0
5   Priya  28.333333  48000.0  Mumbai         3.0
6   Rohan  26.000000  35000.0    Agra         4.5
7   Aisha  29.000000  60000.0   Delhi         6.0

In [53]:
df.isnull().sum()

Name          0
Age           0
Salary        0
City          0
Experience    0
dtype: int64