#Series

A Pandas Series is a one-dimensional, labeled array capable of holding data of any type

In [1]:
!pip install numpy pandas
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (2.2.5)
Requirement already satisfied: pandas in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\pamith\anaconda3\envs\torch_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
strings = ["Alpha","Beta","Gama"]
integers = [10,20,30]
array = np.array([40,50,60])
dictionary = {1:"JAVA" , 2:"PYTHON" , 3:"C++"}

#Priting String

In [3]:
print(pd.Series(strings))

0    Alpha
1     Beta
2     Gama
dtype: object

#print integers

In [4]:
print(pd.Series(integers))

0    10
1    20
2    30
dtype: int64

#Print array

In [5]:
print(pd.Series(array))

0    40
1    50
2    60
dtype: int64

#Print dictionary

In [6]:
print(pd.Series(dictionary))

1      JAVA
2    PYTHON
3       C++
dtype: object

#Replacing Index

In [7]:
print(pd.Series(integers,index = ["a","b","c"]) )#Single inverted commas can be  used too example'a','b'

a    10
b    20
c    30
dtype: int64

#Using diff series for index

In [8]:
print(pd.Series(integers,index = strings))

Alpha    10
Beta     20
Gama     30
dtype: int64

In [9]:
data = {
    "Name": ["Aarav", "Priya", "Rahul"],
    "Salary": [45000, 52000, 48000],
    "City": ["Pune", "Mumbai", "Delhi"]
}

df = pd.DataFrame(data)

df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [10]:
data = [
    ["Aarav", 45000, "Pune"],
    ["Priya", 52000, "Mumbai"],
    ["Rahul", 48000, "Delhi"]
]

df = pd.DataFrame(data, columns=["Name", "Salary", "City"])

df

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai
2  Rahul   48000   Delhi

In [11]:
df["Name"]

0    Aarav
1    Priya
2    Rahul
Name: Name, dtype: object

In [12]:
df[["Name", "Salary"]]

    Name  Salary
0  Aarav   45000
1  Priya   52000
2  Rahul   48000

In [13]:
df.loc[0]

Name      Aarav
Salary    45000
City       Pune
Name: 0, dtype: object

In [14]:
df.loc[0:1]

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai

In [15]:
df.loc[0:1, ["Name", "City"]]

    Name    City
0  Aarav    Pune
1  Priya  Mumbai

In [16]:
df.iloc[0]

Name      Aarav
Salary    45000
City       Pune
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]

    Name  Salary    City
0  Aarav   45000    Pune
1  Priya   52000  Mumbai